sudo: false
language: node_js

notifications:
  email: false

cache:
  yarn: true
  directories:
    - node_modules

os: linux
node_js:
  - '8'
  - '6'

before_script: yarn hela

script: yarn test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - yarn start release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
