sudo: false
language: node_js

notifications:
  email: false

cache:
  yarn: true
  directories:
    - node_modules

os: linux
node_js:
  - '8'
  - '6'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

before_script: yarn link

script: yarn test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - yarn start release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

# TODO: remove when target Node >=8
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "6"
